### ISSUE TITLE
nf_ct_is_untracked

### ISSUE THREAD

**Issue by kravietz** [betolj/ndpi-netfilter#70]
The `` function has been [removed](https://patchwork.ozlabs.org/patch/750924/) from the kernel headers at some point and compilation now returns this:
```
/home/kravietz/ndpi-netfilter/src/main.c: In function ‘ndpi_mt’:
/home/kravietz/ndpi-netfilter/src/main.c:633:13: error: implicit declaration of function ‘nf_ct_is_untracked’ [-Werror=implicit-function-declaration]
  } else if (nf_ct_is_untracked(ct)){
```
Judging from the removal [comments](https://patchwork.ozlabs.org/patch/750924/) it's a no-op so the check could be most likely removed at all.

**Comment by kravietz** [comment]
I have just confirmed in the field that merely commenting out the offending section around line 633 allowed to complete the compilation and nDPI works OK on kernel 4.15.18.

**Comment by Fateassfaker** [comment]
Hi thank you . I get the due result with your method. But I want to ask , do you know some other similar open source frame like this to  block traffic ?

**Comment by Shylockyk** [comment]
@kravietz Hi thank you . I get the due result with your method. But I want to ask , do you know some other similar open source frame like this to block traffic ?

**Comment by kravietz** [comment]
@Fateassfaker No, unfortunately I'm not aware of any alternatives

**Comment by aidyw** [comment]
Ahh, I see someone else came across this issue. I too simply commented out the section too. 
I emailed the repo owner but currently no response. Due to the fact that I'm using nDPI in my iptables rule set every time I upgrade the kernel I must re-compile. To this end I think we should open a new branch to reflect this modification. What do you think?

I'm also a little surprised that it fails anyway, as the comments from the maintainers of the conntrack code where the deprecated function resides, suggested that the function has been deprecated and will always return false. This I think makes sense as then any code such as this which includes the function would continue to compile, but they must have actually removed the function declaration completely and looking at my sources this seems to be true. Ah well, seems we need to patch it up every time.

**Comment by ngocnn97** [comment]
@kravietz  Have you installed ndpi on kernel 4.15 yet? can you show me me ?  My email: nguyenngockma97@gmail.com

**Comment by ngocnn97** [comment]
@aidyw  
Please show me the comment section
